# Generated by Django 5.0.7 on 2026-03-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='expiry_image',
            field=models.ImageField(blank=True, null=True, upload_to='scans/'),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='is_expired',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scans/'),
        ),
    ]
