# Generated by Django 5.0.7 on 2026-03-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imageupload_expiry_image_scanresult_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='nutrition_levels',
            field=models.JSONField(default=dict),
        ),
    ]
